CREATE DATABASE BLINKIT;
USE BLINKIT;

CREATE TABLE B_DATA(
`ITEM FAT CONTENT` ENUM('Low Fat', 'Regular'), 
`ITEM IDENTIFIER` VARCHAR(20),
`ITEM TYPE` VARCHAR(20), 
`OUTLET ESTABLISHMENT YEAR` INT, 
`OUTLET IDENTIFIER` VARCHAR(20),
`OUTLET LOCATION TYPE` ENUM('Tier 1', 'Tier 2', 'Tier 3'), 
`OUTLET SIZE` ENUM('Small', 'Medium', 'High'),
`OUTLET TYPE` VARCHAR(30),
`ITEM VISIBILITY` DECIMAL(12, 10), 
`ITEM WEIGHT` DECIMAL(5, 3),
`SALES` DECIMAL (7, 4), 
RATING INT, 
OUTLET_AGE INT    
);

SELECT * FROM B_DATA;
DESCRIBE B_DATA;

-- distribution of Low Fat vs Regular items
SELECT `ITEM FAT CONTENT`, COUNT(*)
FROM B_DATA
GROUP BY `ITEM FAT CONTENT`;  -- REGULAR 3003 ITEMS, LOW FAT 5516 ITEMS.

-- Which fat category contributes more to total sales?
SELECT 	`ITEM FAT CONTENT`, SUM(SALES) 
FROM B_DATA
GROUP BY `ITEM FAT CONTENT`;   -- LOW FAT CONTRI MORE

-- Which fat category has higher average sales? 
SELECT `ITEM FAT CONTENT`, AVG(SALES)
FROM B_DATA
GROUP BY `ITEM FAT CONTENT`;  -- HIGHER FOR REGULAR.  

-- Does fat content influence sales consistency?
SELECT `ITEM FAT CONTENT`, 
AVG(SALES) AS AVG_SALES, 
STDDEV(SALES) AS STD_DEV, 
(AVG(SALES)/STDDEV(SALES)) AS CONSISTENCY_INDEX
FROM B_DATA
GROUP BY `ITEM FAT CONTENT`;
-- ALMOST IDENTICAL SALES CONSISTENCY. FAT CONTENT FACTOR DOESNT AFFECT THE SALES MUCH. 

-- Are certain fat type products popular in certain outlets?
SELECT `OUTLET TYPE`, `ITEM FAT CONTENT`, COUNT(*) AS Total_Items
FROM B_DATA 
GROUP BY `OUTLET TYPE`, `ITEM FAT CONTENT`
ORDER BY `OUTLET TYPE`, Total_Items DESC;
-- low fat are popular in grocery stores, supermarket type 1, type2, type3. (low fat are popular in all types of outlet types.)

-- How many unique item types exist?
SELECT COUNT(DISTINCT(`ITEM TYPE`)) AS UNIQUE_ITEM_TYPES FROM B_DATA; -- THERE ARE 16 UNIQUE ITEM TYPES.  

-- Which item types are most frequently sold?
SELECT `ITEM TYPE`, COUNT(*) AS FREQUENCY
FROM B_DATA
GROUP BY `ITEM TYPE`   
ORDER BY FREQUENCY DESC;
-- FRUITS AND VEGETABLES, SNACK FOODS, HOUSEHOLDS, FROZEN FOODS ARE MOST FREQUENTLY SOLD.

-- Which item types generate the highest total sales?
-- Which item types have the highest average sales per item?
SELECT `ITEM TYPE`, SUM(SALES) AS TOTAL_SALES
FROM B_DATA
GROUP BY `ITEM TYPE`  
ORDER BY TOTAL_SALES DESC LIMIT 5;
-- Fruits and Vegetable, Snack Foods, HOUSEHOLD, FROZEN, DAIRY.alter

SELECT `ITEM TYPE`, AVG(SALES) AS AVG_SALES
FROM B_DATA
GROUP BY `ITEM TYPE`  
ORDER BY AVG_SALES DESC LIMIT 5;
-- Household, Dairy, Starchy Foods, Snack Foods, Fruits and Vegetable	

-- Are some item types overstocked but underperforming?
SELECT `ITEM TYPE`, AVG(`ITEM VISIBILITY`) AS AVG_VISIBILITY, AVG(SALES) AS AVG_SALES, 
(AVG(SALES)/AVG(`ITEM VISIBILITY`)) AS PERFORMANCE_RATIO 
FROM B_DATA
GROUP BY `ITEM TYPE`
ORDER BY PERFORMANCE_RATIO LIMIT 5;

-- Which item types show high variability in sales?
SELECT `ITEM TYPE`, MIN(SALES) AS MIN_SALES, MAX(SALES) AS MAX_SALES, 
(MAX(SALES)-MIN(SALES)) AS VARIABILITY
FROM B_DATA
GROUP BY `ITEM TYPE` 
ORDER BY VARIABILITY DESC LIMIT 5;
-- Health and Hygiene, Dairy, Frozen Foods, Snack Foods, Household

-- Are there item types with low volume but high revenue?
SELECT `ITEM TYPE`, COUNT(*) AS VOL, SUM(SALES) AS REV, SUM(SALES)/COUNT(*) AS REV_PER_UNIT
FROM B_DATA
GROUP BY `ITEM TYPE` 
ORDER BY REV_PER_UNIT DESC LIMIT 5;
-- Household, Dairy, Starchy Foods, Snack Foods, Fruits and Vegetable

-- What is the distribution of item weights?
SELECT `ITEM TYPE`, MIN(`ITEM WEIGHT`), MAX(`ITEM WEIGHT`), AVG(`ITEM WEIGHT`), STDDEV(`ITEM WEIGHT`) 
FROM B_DATA
GROUP BY `ITEM TYPE`;

-- Are heavier items associated with higher sales? DO THE ITEM WEIGHT AFFECT SALES?
SELECT `ITEM WEIGHT`, AVG(SALES) AS AVG_SALES
FROM B_DATA
GROUP BY `ITEM WEIGHT`
ORDER BY AVG_SALES DESC;
-- NO SALES ARE NOT RELATED TO THE ITEM WEIGHT.

-- How is item visibility distributed across products?
SELECT `ITEM TYPE`, AVG(`ITEM VISIBILITY`) AS AVG_VISIBILITY
FROM B_DATA
GROUP BY `ITEM TYPE`
ORDER BY AVG_VISIBILITY DESC;

-- Does higher visibility always lead to higher sales?
SELECT `ITEM TYPE`, AVG(`ITEM VISIBILITY`) AS AVG_VISIBILITY, AVG(SALES) AS AVG_SALES
FROM B_DATA
GROUP BY `ITEM TYPE`
ORDER BY AVG_SALES DESC;
-- NO, HIGHER VISIBILITY DOESNT ALWAYS LEAD TO HIGHER SALES.

-- Do some item types perform well even with low visibility?
SELECT 
`ITEM TYPE`, 
AVG(SALES) AS AVG_SALES,
AVG(`ITEM VISIBILITY`) AS AVG_VISIBILITY
FROM B_DATA
WHERE `ITEM VISIBILITY` < 0.05 
GROUP BY `ITEM TYPE`
ORDER BY AVG_SALES DESC;

-- How many outlet types exist in the dataset?
SELECT COUNT(DISTINCT `OUTLET TYPE`) FROM B_DATA;  -- 4

-- Which outlet type carries the most items?
SELECT `OUTLET TYPE`, COUNT(*) 
FROM B_DATA 
GROUP BY `OUTLET TYPE` 
ORDER BY COUNT(*) DESC LIMIT 1;  -- SUPERMARKET TYPE 1

-- Which outlet type generates the highest total sales?
SELECT `OUTLET TYPE`, SUM(SALES)
FROM B_DATA
GROUP BY `OUTLET TYPE` 
ORDER BY SUM(SALES) DESC LIMIT 1;    -- SUPERMARKET TYPE 1

-- Is sales performance consistent across outlet types?
-- Do grocery stores behave differently from supermarkets?
SELECT `OUTLET TYPE`, SUM(SALES)
FROM B_DATA
GROUP BY `OUTLET TYPE` 
ORDER BY SUM(SALES) DESC; 
-- HIGHEST SALES IN SUPERMARKET TYPE 1 (VERY HIGH.)
-- GROCERY STORE IS THE NEXT HIGHEST
-- SUPERMARKET TYPE 2 AND 3 ARE COMPARABLE. 
-- NO, GROCERY STORES BEHAVE ALMOST COMPARABLE TO TYPE 2 AND 3 SUPERMARKETS, BUT THEIR SALES ARE SIGNIFICANTLY LESSER THAN TYPE 1 SUPERMARKET. 

-- Do larger outlets always generate more sales?
SELECT `OUTLET SIZE`, AVG(SALES) AS AVG_SALES
FROM B_DATA
GROUP BY `OUTLET SIZE` 
ORDER BY AVG_SALES DESC;
-- LARGE OUTLETS GENERATE HIGHEST SALES, WHERAS MEDIUM SIZED OUTLETS GENERATE THE LEAST SALES.  

-- Which outlet size has the best sales efficiency (sales per item)?
SELECT `OUTLET SIZE`, AVG(SALES) AS AVG_SALES, COUNT(*) AS NUM_OF_ITEMS, (AVG(SALES)/COUNT(*)) AS SALES_PER_ITEM
FROM B_DATA 
GROUP BY `OUTLET SIZE`
ORDER BY SALES_PER_ITEM DESC; 
-- LARGE OUTLET SIZE HAS THE HIGHEST SALES PER ITEM, LOWEST IN MEDIUM SIZED OUTLETS.

-- DOES OUTLET AGE AFFECT CUSTOMER'S PURCHASING BEHAVIOUR?
SELECT OUTLET_AGE, AVG(SALES) AS AVG_SALES
FROM B_DATA 
GROUP BY OUTLET_AGE
ORDER BY AVG_SALES;
-- NO IT DOESNT AFFECT.

-- Which tier generates the highest total sales?
SELECT `OUTLET LOCATION TYPE`,  SUM(SALES) AS TOTAL_SALES
FROM B_DATA 
GROUP BY `OUTLET LOCATION TYPE` 
ORDER BY TOTAL_SALES DESC LIMIT 1;
-- TIER 3

-- Which tier has the highest average sales?
SELECT `OUTLET LOCATION TYPE`,  AVG(SALES) AS AVG_SALES
FROM B_DATA 
GROUP BY `OUTLET LOCATION TYPE` 
ORDER BY AVG_SALES DESC LIMIT 1;
-- TIER 2  

-- Are Tier 3 outlets compensating lower prices with higher volume?
SELECT `OUTLET LOCATION TYPE`, COUNT(*) AS TOTAL_VOLUME, AVG(SALES) AS AVERAGE_SALES
FROM B_DATA
GROUP BY `OUTLET LOCATION TYPE`
ORDER BY AVERAGE_SALES;
-- YES, TOTAL VOLUME OF TIER 3 IS HIGHER AS COMPARED TO TIER 1 AND 2.

-- Which combinations of item type + outlet type perform best?
SELECT `ITEM TYPE`, `OUTLET TYPE`, SUM(SALES) AS TOTAL_SALES
FROM B_DATA 
GROUP BY `ITEM TYPE`, `OUTLET TYPE`
ORDER BY TOTAL_SALES DESC;

-- WHICH ITEMS SHOULD BLINKIT PRIORITIZE FOR PROMOTION?
SELECT `ITEM TYPE`, AVG(SALES) AS AVERAGE_SALES 
FROM B_DATA 
GROUP BY `ITEM TYPE` 
ORDER BY AVERAGE_SALES DESC;

-- WHICH LOW-VISIBILITY ITEMS HAVE HIGH SALES? (PROMOTION OPPORTUNITY)
SELECT `ITEM TYPE`, AVG(`ITEM VISIBILITY`) AS AVG_VISIBILITY, SUM(SALES) AS TOTAL_SALES
FROM B_DATA 
WHERE `ITEM VISIBILITY`<0.05
GROUP BY `ITEM TYPE`
ORDER BY TOTAL_SALES DESC;

-- WHICH OUTLET TYPES SHOULD BLINKIT EXPAND?
SELECT `OUTLET TYPE`, AVG(SALES) AS AVG_SALES, (AVG(SALES) / AVG(`ITEM VISIBILITY`)) AS EFFICIENCY
FROM B_DATA
GROUP BY `OUTLET TYPE` 
ORDER BY EFFICIENCY DESC;
-- TYPE 3 SUPERMARKETS ARE MPRE EFFICIENT, SO MORE SUCH SUPERMARKETS CAN BE ESTABLISHED FOR BETTER GROWTH.

-- WHICH ITEM TYPES PERFORM BEST IN EACH TIER?
SELECT `ITEM TYPE`, `OUTLET LOCATION TYPE`, AVG(SALES) AS AVG_SALES, (AVG(SALES) / AVG(`ITEM VISIBILITY`)) AS EFFICIENCY
FROM B_DATA 
GROUP BY `OUTLET LOCATION TYPE` , `ITEM TYPE`
ORDER BY EFFICIENCY DESC;

-- WHICH COMBINATIONS SHOULD BE PROMOTED MOST?
SELECT `ITEM TYPE`, `OUTLET TYPE`, ROUND(SUM(SALES),2) AS TOTAL_SALES
FROM B_DATA
GROUP BY `ITEM TYPE`, `OUTLET TYPE`
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- WHICH ITEMS SHOULD BE REMOVED OR RECONSIDERED?
SELECT `ITEM TYPE`, `OUTLET TYPE`, ROUND(AVG(SALES),2) AS AVG_SALES
FROM B_DATA
GROUP BY `ITEM TYPE`, `OUTLET TYPE`
ORDER BY AVG_SALES ASC
LIMIT 10;